# This file created by conda-build 2.1.2
# meta.yaml template originally from:
# /Users/travis/build/conda-forge/click-feedstock/recipe, last modified Mon Feb  6 10:15:36 2017
# ------------------------------------------------

package:
    name: click
    version: '6.7'
source:
    fn: click-6.7.tar.gz
    sha256: f15516df478d5a56180fbf80e68f206010e6d160fc39fa508b65e035fd75130b
    url: https://pypi.io/packages/source/c/click/click-6.7.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py27_0
requirements:
    build: []
    run:
        - python
test:
    imports:
        - click
about:
    dev_url: https://github.com/pallets/click
    doc_url: http://click.pocoo.org/
    home: http://click.pocoo.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A simple wrapper around optparse for powerful command line utilities.
extra:
    recipe-maintainers:
        - pmlandwehr
