# This file created by conda-build 2.1.10
# meta.yaml template originally from:
# /Users/travis/build/conda-forge/h5py-feedstock/recipe, last modified Fri Jun  9 21:50:48 2017
# ------------------------------------------------

package:
    name: h5py
    version: 2.7.0
source:
    fn: h5py-2.7.0.tar.gz
    sha256: fff3a878c6adfa1b4f5c30b558a295d52dd4fee9174128c626ef416dec1b536b
    url: https://github.com/h5py/h5py/archive/2.7.0.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '1'
    string: np113py27_1
requirements:
    build:
        - blas 1.1 openblas
        - ca-certificates 2017.4.17 0
        - certifi 2017.4.17 py27_0
        - cython 0.25.2 py27_1
        - hdf5 1.8.18 0
        - libgfortran 3.0.0 0
        - ncurses 5.9 10
        - numpy 1.13.0 py27_blas_openblas_200
        - openblas 0.2.19 2
        - openssl 1.0.2k 0
        - pkg-config 0.29.1 1
        - pkgconfig 1.2.2 py27_1
        - python 2.7.13 1
        - readline 6.2 0
        - setuptools 33.1.1 py27_0
        - six 1.10.0 py27_1
        - sqlite 3.13.0 1
        - tk 8.5.19 1
        - zlib 1.2.11 0
    run:
        - python
        - numpy x.x
        - hdf5 1.8.18|1.8.18.*
        - six
test:
    imports:
        - h5py
about:
    home: http://www.h5py.org/
    license: BSD 3-Clause
    license_file: licenses/license.txt
    summary: Read and write HDF5 files from Python.
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - pitrou
        - tacaswell
