# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /Users/travis/build/conda-forge/tqdm-feedstock/recipe, last modified Mon Jul 24 02:24:48 2017
# ------------------------------------------------

package:
    name: tqdm
    version: 4.15.0
source:
    fn: tqdm-4.15.0.tar.gz
    sha256: 6ec1dc74efacf2cda936b4a6cf4082ce224c76763bdec9f17e437c8cfcaa9953
    url: https://pypi.io/packages/source/t/tqdm/tqdm-4.15.0.tar.gz
build:
    entry_points:
        - tqdm=tqdm._main:main
    noarch: ''
    noarch_python: false
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py27_0
requirements:
    build:
        - ca-certificates 2017.4.17 0
        - certifi 2017.4.17 py27_0
        - ncurses 5.9 10
        - openssl 1.0.2l 0
        - python 2.7.13 1
        - readline 6.2 0
        - setuptools 36.2.0 py27_0
        - sqlite 3.13.0 1
        - tk 8.5.19 1
        - zlib 1.2.11 0
    run:
        - python
test:
    commands:
        - tqdm --help
        - tqdm -v
    imports:
        - tqdm
about:
    dev_url: https://github.com/tqdm/tqdm
    doc_url: https://github.com/tqdm/tqdm
    home: https://pypi.python.org/pypi/tqdm
    license: MPLv2.0, MIT
    license_family: MIT
    license_file: LICENCE
    summary: A Fast, Extensible Progress Meter
extra:
    final: true
    recipe-maintainers:
        - casperdcl
        - lrq3000
        - pmlandwehr
        - ericdill
