# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /Users/travis/build/conda-forge/libgpuarray-feedstock/recipe, last modified Wed Jul 26 17:21:49 2017
# ------------------------------------------------

package:
    name: libgpuarray
    version: 0.6.9
source:
    fn: libgpuarray-0.6.9.tar.gz
    sha256: 689716feecb4e495f4d383ec1518cf3ba70a2a642a903cc445b6b6ffc119bc25
    url: https://github.com/Theano/libgpuarray/archive/v0.6.9.tar.gz
build:
    features: ''
    noarch: ''
    noarch_python: false
    number: '0'
    string: '0'
requirements:
    build:
        - bzip2 1.0.6 1
        - ca-certificates 2017.4.17 0
        - cmake 3.8.0 2
        - curl 7.54.1 0
        - expat 2.2.1 0
        - krb5 1.14.2 0
        - libssh2 1.8.0 1
        - libuv 1.11.0 0
        - ncurses 5.9 10
        - openssl 1.0.2l 0
        - rhash 1.3.4 0
        - toolchain 2.0.0 0
        - xz 5.2.2 0
        - zlib 1.2.11 0
    run: []
test:
    commands:
        - test -f ${PREFIX}/lib/libgpuarray.dylib
    requires: ''
about:
    dev_url: http://github.com/Theano/libgpuarray
    doc_url: http://deeplearning.net/software/libgpuarray/
    home: http://github.com/Theano/libgpuarray
    license: ISC
    license_file: LICENSE
    summary: Library to manipulate arrays on GPU
extra:
    final: true
    recipe-maintainers:
        - abergeron
