# NCAA 2015-16: http://stats.ncaa.org/team/index/12260?org_id=<NCAA_NUM>
# ESPN 2015-16: http://espn.go.com/mens-college-basketball/team/roster/_/id/<ESPN_NUM>
"""
Conference is something that can be done automatically via sports-reference main team page
"""
teams = [{'kaggle_id': 1101, 'team_name': "Abilene Chr", 'sports-reference': 'abilene-christian'},
{'kaggle_id': 1102, 'team_name': "Air Force", 'sports-reference': 'air-force'},
{'kaggle_id': 1103, 'team_name': "Akron", 'sports-reference': 'akron'},
{'kaggle_id': 1104, 'team_name': "Alabama", 'sports-reference': 'alabama'},
{'kaggle_id': 1105, 'team_name': "Alabama A&M", 'sports-reference': 'alabama-am'},
{'kaggle_id': 1106, 'team_name': "Alabama St", 'sports-reference': 'alabama-state'},
{'kaggle_id': 1107, 'team_name': "Albany NY", 'sports-reference': 'albany-ny'},
{'kaggle_id': 1108, 'team_name': "Alcorn St", 'sports-reference': 'alcorn-state'},
#{'kaggle_id': 1109, 'team_name': "Alliant Intl"}, --  not in existence since 1992
{'kaggle_id': 1110, 'team_name': "American Univ", 'sports-reference': 'american'},
{'kaggle_id': 1111, 'team_name': "Appalachian St", 'sports-reference': 'appalachian-state'},
{'kaggle_id': 1112, 'team_name': "Arizona", 'sports-reference': 'arizona'},
{'kaggle_id': 1113, 'team_name': "Arizona St", 'sports-reference': 'arizona-state'},
{'kaggle_id': 1114, 'team_name': "Ark Little Rock", 'sports-reference': 'arkansas-little-rock'},
{'kaggle_id': 1115, 'team_name': "Ark Pine Bluff", 'sports-reference': 'arkansas-pine-bluff'},
{'kaggle_id': 1116, 'team_name': "Arkansas", 'sports-reference': 'arkansas'},
{'kaggle_id': 1117, 'team_name': "Arkansas St", 'sports-reference': 'arkansas-state'},
#{'kaggle_id': 1118, 'team_name': "Armstrong St", 'sports-reference': 'armstrong', 'conference', 'big_south'}, -- gone since 1987
{'kaggle_id': 1119, 'team_name': "Army", 'sports-reference': 'army'},
{'kaggle_id': 1120, 'team_name': "Auburn", 'sports-reference': 'auburn'},
#{'kaggle_id': 1121, 'team_name': "Augusta", 'sports-reference': 'augusta-state'}, -- gone since 1991
{'kaggle_id': 1122, 'team_name': "Austin Peay", 'sports-reference': 'austin-peay'},
{'kaggle_id': 1123, 'team_name': "Ball St", 'sports-reference': 'ball-state'},
{'kaggle_id': 1124, 'team_name': "Baylor", 'sports-reference': 'baylor'},
{'kaggle_id': 1125, 'team_name': "Belmont", 'sports-reference': 'belmont'},
{'kaggle_id': 1126, 'team_name': "Bethune-Cookman", 'sports-reference': 'bethune-cookman'},
{'kaggle_id': 1127, 'team_name': "Binghamton", 'sports-reference': 'binghamton'},
{'kaggle_id': 1128, 'team_name': "Birmingham So", 'sports-reference': 'birmingham-southern'}, # gone after 2006
{'kaggle_id': 1129, 'team_name': "Boise St", 'sports-reference': 'boise-state'},
{'kaggle_id': 1130, 'team_name': "Boston College", 'sports-reference': 'boston-college'},
{'kaggle_id': 1131, 'team_name': "Boston Univ", 'sports-reference': 'boston-university'},
{'kaggle_id': 1132, 'team_name': "Bowling Green", 'sports-reference': 'bowling-green-state'},
{'kaggle_id': 1133, 'team_name': "Bradley", 'sports-reference': 'bradley'},
{'kaggle_id': 1134, 'team_name': "Brooklyn", 'sports-reference': 'brooklyn'}, # gone after 1992
{'kaggle_id': 1135, 'team_name': "Brown", 'sports-reference': 'brown'},
{'kaggle_id': 1136, 'team_name': "Bryant", 'sports-reference': 'bryant'},
{'kaggle_id': 1137, 'team_name': "Bucknell", 'sports-reference': 'bucknell'},
{'kaggle_id': 1138, 'team_name': "Buffalo", 'sports-reference': 'buffalo'},
{'kaggle_id': 1139, 'team_name': "Butler", 'sports-reference': 'butler'},
{'kaggle_id': 1140, 'team_name': "BYU", 'sports-reference': 'brigham-young'},
{'kaggle_id': 1141, 'team_name': "C Michigan", 'sports-reference': 'central-michigan'},
{'kaggle_id': 1142, 'team_name': "Cal Poly SLO", 'sports-reference': 'cal-poly'},
{'kaggle_id': 1143, 'team_name': "California", 'sports-reference': 'california'},
{'kaggle_id': 1144, 'team_name': "Campbell", 'sports-reference': 'campbell'},
{'kaggle_id': 1145, 'team_name': "Canisius", 'sports-reference': 'canisius'},
{'kaggle_id': 1146, 'team_name': "Cent Arkansas", 'sports-reference': 'central-arkansas'},
{'kaggle_id': 1147, 'team_name': "Centenary", 'sports-reference': 'centenary-la'}, # gone after 2011
{'kaggle_id': 1148, 'team_name': "Central Conn", 'sports-reference': 'central-connecticut-state'},
{'kaggle_id': 1149, 'team_name': "Charleston So", 'sports-reference': 'charleston-southern'},
{'kaggle_id': 1150, 'team_name': "Charlotte", 'sports-reference': 'charlotte'},
{'kaggle_id': 1151, 'team_name': "Chattanooga", 'sports-reference': 'chattanooga'},
{'kaggle_id': 1152, 'team_name': "Chicago St", 'sports-reference': 'chicago-state'},
{'kaggle_id': 1153, 'team_name': "Cincinnati", 'sports-reference': 'cincinnati'},
{'kaggle_id': 1154, 'team_name': "Citadel", 'sports-reference': 'citadel'},
{'kaggle_id': 1155, 'team_name': "Clemson", 'sports-reference': 'clemson'},
{'kaggle_id': 1156, 'team_name': "Cleveland St", 'sports-reference': 'cleveland-state'},
{'kaggle_id': 1157, 'team_name': "Coastal Car", 'sports-reference': 'coastal-carolina'},
{'kaggle_id': 1158, 'team_name': "Col Charleston", 'sports-reference': 'college-of-charleston'},
{'kaggle_id': 1159, 'team_name': "Colgate", 'sports-reference': 'colgate'},
{'kaggle_id': 1160, 'team_name': "Colorado", 'sports-reference': 'colorado'},
{'kaggle_id': 1161, 'team_name': "Colorado St", 'sports-reference': 'colorado-state'},
{'kaggle_id': 1162, 'team_name': "Columbia", 'sports-reference': 'columbia'},
{'kaggle_id': 1163, 'team_name': "Connecticut", 'sports-reference': 'connecticut'},
{'kaggle_id': 1164, 'team_name': "Coppin St", 'sports-reference': 'coppin-state'},
{'kaggle_id': 1165, 'team_name': "Cornell", 'sports-reference': 'cornell'},
{'kaggle_id': 1166, 'team_name': "Creighton", 'sports-reference': 'creighton'},
{'kaggle_id': 1167, 'team_name': "CS Bakersfield", 'sports-reference': 'cal-state-bakersfield'},
{'kaggle_id': 1168, 'team_name': "CS Fullerton", 'sports-reference': 'cal-state-fullerton'},
{'kaggle_id': 1169, 'team_name': "CS Northridge", 'sports-reference': 'cal-state-northridge'},
{'kaggle_id': 1170, 'team_name': "CS Sacramento", 'sports-reference': 'sacramento-state'},
{'kaggle_id': 1171, 'team_name': "Dartmouth", 'sports-reference': 'dartmouth'},
{'kaggle_id': 1172, 'team_name': "Davidson", 'sports-reference': 'davidson'},
{'kaggle_id': 1173, 'team_name': "Dayton", 'sports-reference': 'dayton'},
{'kaggle_id': 1174, 'team_name': "Delaware", 'sports-reference': 'delaware'},
{'kaggle_id': 1175, 'team_name': "Delaware St", 'sports-reference': 'delaware-state'},
{'kaggle_id': 1176, 'team_name': "Denver", 'sports-reference': 'denver'},
{'kaggle_id': 1177, 'team_name': "DePaul", 'sports-reference': 'depaul'},
{'kaggle_id': 1178, 'team_name': "Detroit", 'sports-reference': 'detroit-mercy'}, # this might be wrong
{'kaggle_id': 1179, 'team_name': "Drake", 'sports-reference': 'drake'},
{'kaggle_id': 1180, 'team_name': "Drexel", 'sports-reference': 'drexel'},
{'kaggle_id': 1181, 'team_name': "Duke", 'sports-reference': 'duke'},
{'kaggle_id': 1182, 'team_name': "Duquesne", 'sports-reference': 'duquesne'},
{'kaggle_id': 1183, 'team_name': "E Illinois", 'sports-reference': 'eastern-illinois'},
{'kaggle_id': 1184, 'team_name': "E Kentucky", 'sports-reference': 'eastern-kentucky'},
{'kaggle_id': 1185, 'team_name': "E Michigan", 'sports-reference': 'eastern-michigan'},
{'kaggle_id': 1186, 'team_name': "E Washington", 'sports-reference': 'eastern-washington'},
{'kaggle_id': 1187, 'team_name': "East Carolina", 'sports-reference': 'east-carolina'},
{'kaggle_id': 1188, 'team_name': "Edwardsville", 'sports-reference': 'southern-illinois-edwardsville'},
{'kaggle_id': 1189, 'team_name': "Elon", 'sports-reference': 'elon'},
{'kaggle_id': 1190, 'team_name': "ETSU", 'sports-reference': 'east-tennessee-state'},
{'kaggle_id': 1191, 'team_name': "Evansville", 'sports-reference': 'evansville'},
{'kaggle_id': 1192, 'team_name': "F Dickinson", 'sports-reference': 'fairleigh-dickinson'},
{'kaggle_id': 1193, 'team_name': "Fairfield", 'sports-reference': 'fairfield'},
{'kaggle_id': 1194, 'team_name': "FL Atlantic", 'sports-reference': 'florida-atlantic'},
{'kaggle_id': 1195, 'team_name': "FL Gulf Coast", 'sports-reference': 'florida-gulf-coast'},
{'kaggle_id': 1196, 'team_name': "Florida", 'sports-reference': 'florida'},
{'kaggle_id': 1197, 'team_name': "Florida A&M", 'sports-reference': 'florida-am'},
{'kaggle_id': 1198, 'team_name': "Florida Intl", 'sports-reference': 'florida-international'},
{'kaggle_id': 1199, 'team_name': "Florida St", 'sports-reference': 'florida-state'},
{'kaggle_id': 1200, 'team_name': "Fordham", 'sports-reference': 'fordham'},
{'kaggle_id': 1201, 'team_name': "Fresno St", 'sports-reference': 'fresno-state'},
{'kaggle_id': 1202, 'team_name': "Furman", 'sports-reference': 'furman'},
{'kaggle_id': 1203, 'team_name': "G Washington", 'sports-reference': 'george-washington'},
{'kaggle_id': 1204, 'team_name': "Ga Southern", 'sports-reference': 'georgia-southern'},
{'kaggle_id': 1205, 'team_name': "Gardner Webb", 'sports-reference': 'gardner-webb'},
{'kaggle_id': 1206, 'team_name': "George Mason", 'sports-reference': 'george-mason'},
{'kaggle_id': 1207, 'team_name': "Georgetown", 'sports-reference': 'georgetown'},
{'kaggle_id': 1208, 'team_name': "Georgia", 'sports-reference': 'georgia'},
{'kaggle_id': 1209, 'team_name': "Georgia St", 'sports-reference': 'georgia-state'},
{'kaggle_id': 1210, 'team_name': "Georgia Tech", 'sports-reference': 'georgia-tech'},
{'kaggle_id': 1211, 'team_name': "Gonzaga", 'sports-reference': 'gonzaga'},
{'kaggle_id': 1212, 'team_name': "Grambling", 'sports-reference': 'grambling'},
{'kaggle_id': 1213, 'team_name': "Grand Canyon", 'sports-reference': 'grand-canyon'},
{'kaggle_id': 1214, 'team_name': "Hampton", 'sports-reference': 'hampton'},
#{'kaggle_id': 1215, 'team_name': "Hardin-Simmons", 'sports-reference': 'hardin-simmons'}, -- gone since 1990
{'kaggle_id': 1216, 'team_name': "Hartford", 'sports-reference': 'hartford'},
{'kaggle_id': 1217, 'team_name': "Harvard", 'sports-reference': 'harvard'},
{'kaggle_id': 1218, 'team_name': "Hawaii", 'sports-reference': 'hawaii'},
{'kaggle_id': 1219, 'team_name': "High Point", 'sports-reference': 'high-point'},
{'kaggle_id': 1220, 'team_name': "Hofstra", 'sports-reference': 'hofstra'},
{'kaggle_id': 1221, 'team_name': "Holy Cross", 'sports-reference': 'holy-cross'},
{'kaggle_id': 1222, 'team_name': "Houston", 'sports-reference': 'houston'},
{'kaggle_id': 1223, 'team_name': "Houston Bap", 'sports-reference': 'houston-baptist'},
{'kaggle_id': 1224, 'team_name': "Howard", 'sports-reference': 'howard'},
{'kaggle_id': 1225, 'team_name': "Idaho", 'sports-reference': 'idaho'},
{'kaggle_id': 1226, 'team_name': "Idaho St", 'sports-reference': 'idaho-state'},
{'kaggle_id': 1227, 'team_name': "IL Chicago", 'sports-reference': 'illinois-chicago'},
{'kaggle_id': 1228, 'team_name': "Illinois", 'sports-reference': 'illinois'},
{'kaggle_id': 1229, 'team_name': "Illinois St", 'sports-reference': 'illinois-state'},
{'kaggle_id': 1230, 'team_name': "Incarnate Word", 'sports-reference': 'incarnate-word'},
{'kaggle_id': 1231, 'team_name': "Indiana", 'sports-reference': 'indiana'},
{'kaggle_id': 1232, 'team_name': "Indiana St", 'sports-reference': 'indiana-state'},
{'kaggle_id': 1233, 'team_name': "Iona", 'sports-reference': 'iona'},
{'kaggle_id': 1234, 'team_name': "Iowa", 'sports-reference': 'iowa'},
{'kaggle_id': 1235, 'team_name': "Iowa St", 'sports-reference': 'iowa-state'},
{'kaggle_id': 1236, 'team_name': "IPFW", 'sports-reference': 'ipfw'},
{'kaggle_id': 1237, 'team_name': "IUPUI", 'sports-reference': 'iupui'},
{'kaggle_id': 1238, 'team_name': "Jackson St", 'sports-reference': 'jackson-state'},
{'kaggle_id': 1239, 'team_name': "Jacksonville", 'sports-reference': 'jacksonville'},
{'kaggle_id': 1240, 'team_name': "Jacksonville St", 'sports-reference': 'jacksonville-state'},
{'kaggle_id': 1241, 'team_name': "James Madison", 'sports-reference': 'james-madison'},
{'kaggle_id': 1242, 'team_name': "Kansas", 'sports-reference': 'kansas'},
{'kaggle_id': 1243, 'team_name': "Kansas St", 'sports-reference': 'kansas-state'},
{'kaggle_id': 1244, 'team_name': "Kennesaw", 'sports-reference': 'kennesaw-state'},
{'kaggle_id': 1245, 'team_name': "Kent", 'sports-reference': 'kent-state'},
{'kaggle_id': 1246, 'team_name': "Kentucky", 'sports-reference': 'kentucky'},
{'kaggle_id': 1247, 'team_name': "La Salle", 'sports-reference': 'la-salle'},
{'kaggle_id': 1248, 'team_name': "Lafayette", 'sports-reference': 'lafayette'},
{'kaggle_id': 1249, 'team_name': "Lamar", 'sports-reference': 'lamar'},
{'kaggle_id': 1250, 'team_name': "Lehigh", 'sports-reference': 'lehigh'},
{'kaggle_id': 1251, 'team_name': "Liberty", 'sports-reference': 'liberty'},
{'kaggle_id': 1252, 'team_name': "Lipscomb", 'sports-reference': 'lipscomb'},
{'kaggle_id': 1253, 'team_name': "Long Beach St", 'sports-reference': 'long-beach-state'},
{'kaggle_id': 1254, 'team_name': "Long Island", 'sports-reference': 'long-island-university'},
{'kaggle_id': 1255, 'team_name': "Longwood", 'sports-reference': 'longwood'},
{'kaggle_id': 1256, 'team_name': "Louisiana Tech", 'sports-reference': 'louisiana-tech'},
{'kaggle_id': 1257, 'team_name': "Louisville", 'sports-reference': 'louisville'},
{'kaggle_id': 1258, 'team_name': "Loy Marymount", 'sports-reference': 'loyola-marymount'},
{'kaggle_id': 1259, 'team_name': "Loyola MD", 'sports-reference': 'loyola-md'},
{'kaggle_id': 1260, 'team_name': "Loyola-Chicago", 'sports-reference': 'loyola-il'},
{'kaggle_id': 1261, 'team_name': "LSU", 'sports-reference': 'louisiana-state'},
{'kaggle_id': 1262, 'team_name': "MA Lowell", 'sports-reference': 'massachusetts-lowell'},
{'kaggle_id': 1263, 'team_name': "Maine", 'sports-reference': 'maine'},
{'kaggle_id': 1264, 'team_name': "Manhattan", 'sports-reference': 'manhattan'},
{'kaggle_id': 1265, 'team_name': "Marist", 'sports-reference': 'marist'},
{'kaggle_id': 1266, 'team_name': "Marquette", 'sports-reference': 'marquette'},
{'kaggle_id': 1267, 'team_name': "Marshall", 'sports-reference': 'marshall'},
{'kaggle_id': 1268, 'team_name': "Maryland", 'sports-reference': 'maryland'},
{'kaggle_id': 1269, 'team_name': "Massachusetts", 'sports-reference': 'massachusetts'},
{'kaggle_id': 1270, 'team_name': "McNeese St", 'sports-reference': 'mcneese-state'},
{'kaggle_id': 1271, 'team_name': "MD E Shore", 'sports-reference': 'maryland-eastern-shore'},
{'kaggle_id': 1272, 'team_name': "Memphis", 'sports-reference': 'memphis'},
{'kaggle_id': 1273, 'team_name': "Mercer", 'sports-reference': 'mercer'},
{'kaggle_id': 1274, 'team_name': "Miami FL", 'sports-reference': 'miami-fl'},
{'kaggle_id': 1275, 'team_name': "Miami OH", 'sports-reference': 'miami-oh'},
{'kaggle_id': 1276, 'team_name': "Michigan", 'sports-reference': 'michigan'},
{'kaggle_id': 1277, 'team_name': "Michigan St", 'sports-reference': 'michigan-state'},
{'kaggle_id': 1278, 'team_name': "Minnesota", 'sports-reference': 'minnesota'},
{'kaggle_id': 1279, 'team_name': "Mississippi", 'sports-reference': 'mississippi'},
{'kaggle_id': 1280, 'team_name': "Mississippi St", 'sports-reference': 'mississippi-state'},
{'kaggle_id': 1281, 'team_name': "Missouri", 'sports-reference': 'missouri'},
{'kaggle_id': 1282, 'team_name': "Missouri KC", 'sports-reference': 'missouri-kansas-city'},
{'kaggle_id': 1283, 'team_name': "Missouri St", 'sports-reference': 'missouri-state'},
{'kaggle_id': 1284, 'team_name': "Monmouth NJ", 'sports-reference': 'monmouth'},
{'kaggle_id': 1285, 'team_name': "Montana", 'sports-reference': 'montana'},
{'kaggle_id': 1286, 'team_name': "Montana St", 'sports-reference': 'montana-state'},
{'kaggle_id': 1287, 'team_name': "Morehead St", 'sports-reference': 'morehead-state'},
{'kaggle_id': 1288, 'team_name': "Morgan St", 'sports-reference': 'morgan-state'},
{'kaggle_id': 1289, 'team_name': "Morris Brown", 'sports-reference': 'morris-brown'}, # gone since 2003
{'kaggle_id': 1290, 'team_name': "MS Valley St", 'sports-reference': 'mississippi-valley-state'},
{'kaggle_id': 1291, 'team_name': "Mt St Mary's", 'sports-reference': 'mount-st-marys'},
{'kaggle_id': 1292, 'team_name': "MTSU", 'sports-reference': 'middle-tennessee'},
{'kaggle_id': 1293, 'team_name': "Murray St", 'sports-reference': 'murray-state'},
{'kaggle_id': 1294, 'team_name': "N Colorado", 'sports-reference': 'northern-colorado'},
{'kaggle_id': 1295, 'team_name': "N Dakota St", 'sports-reference': 'north-dakota-state'},
{'kaggle_id': 1296, 'team_name': "N Illinois", 'sports-reference': 'northern-illinois'},
{'kaggle_id': 1297, 'team_name': "N Kentucky", 'sports-reference': 'northern-kentucky'},
{'kaggle_id': 1298, 'team_name': "Navy", 'sports-reference': 'navy'},
{'kaggle_id': 1299, 'team_name': "NC A&T", 'sports-reference': 'north-carolina-at'},
{'kaggle_id': 1300, 'team_name': "NC Central", 'sports-reference': 'north-carolina-central'},
{'kaggle_id': 1301, 'team_name': "NC State", 'sports-reference': 'north-carolina-state'},
{'kaggle_id': 1302, 'team_name': "NE Illinois", 'sports-reference': 'northeastern-illinois'}, # gone since 1998
{'kaggle_id': 1303, 'team_name': "NE Omaha", 'sports-reference': 'nebraska-omaha'},
{'kaggle_id': 1304, 'team_name': "Nebraska", 'sports-reference': 'nebraska'},
{'kaggle_id': 1305, 'team_name': "Nevada", 'sports-reference': 'nevada'},
{'kaggle_id': 1306, 'team_name': "New Hampshire", 'sports-reference': 'new-hampshire'},
{'kaggle_id': 1307, 'team_name': "New Mexico", 'sports-reference': 'new-mexico'},
{'kaggle_id': 1308, 'team_name': "New Mexico St", 'sports-reference': 'new-mexico-state'},
{'kaggle_id': 1309, 'team_name': "New Orleans", 'sports-reference': 'new-orleans'},
{'kaggle_id': 1310, 'team_name': "Niagara", 'sports-reference': 'niagara'},
{'kaggle_id': 1311, 'team_name': "Nicholls St", 'sports-reference': 'nicholls-state'},
{'kaggle_id': 1312, 'team_name': "NJIT", 'sports-reference': 'njit'},
{'kaggle_id': 1313, 'team_name': "Norfolk St", 'sports-reference': 'norfolk-state'},
{'kaggle_id': 1314, 'team_name': "North Carolina", 'sports-reference': 'north-carolina'},
{'kaggle_id': 1315, 'team_name': "North Dakota", 'sports-reference': 'north-dakota'},
{'kaggle_id': 1316, 'team_name': "North Florida", 'sports-reference': 'north-florida'},
{'kaggle_id': 1317, 'team_name': "North Texas", 'sports-reference': 'north-texas'},
{'kaggle_id': 1318, 'team_name': "Northeastern", 'sports-reference': 'northeastern'},
{'kaggle_id': 1319, 'team_name': "Northern Arizona", 'sports-reference': 'northern-arizona'},
{'kaggle_id': 1320, 'team_name': "Northern Iowa", 'sports-reference': 'northern-iowa'},
{'kaggle_id': 1321, 'team_name': "Northwestern", 'sports-reference': 'northwestern'},
{'kaggle_id': 1322, 'team_name': "Northwestern LA", 'sports-reference': 'northwestern-state'},
{'kaggle_id': 1323, 'team_name': "Notre Dame", 'sports-reference': 'notre-dame'},
{'kaggle_id': 1324, 'team_name': "Oakland", 'sports-reference': 'oakland'},
{'kaggle_id': 1325, 'team_name': "Ohio", 'sports-reference': 'ohio'},
{'kaggle_id': 1326, 'team_name': "Ohio St", 'sports-reference': 'ohio-state'},
{'kaggle_id': 1327, 'team_name': "Okla City", 'sports-reference': 'oklahoma-city'}, # gone since 1985
{'kaggle_id': 1328, 'team_name': "Oklahoma", 'sports-reference': 'oklahoma'},
{'kaggle_id': 1329, 'team_name': "Oklahoma St", 'sports-reference': 'oklahoma-state'},
{'kaggle_id': 1330, 'team_name': "Old Dominion", 'sports-reference': 'old-dominion'},
{'kaggle_id': 1331, 'team_name': "Oral Roberts", 'sports-reference': 'oral-roberts'},
{'kaggle_id': 1332, 'team_name': "Oregon", 'sports-reference': 'oregon'},
{'kaggle_id': 1333, 'team_name': "Oregon St", 'sports-reference': 'oregon-state'},
{'kaggle_id': 1334, 'team_name': "Pacific", 'sports-reference': 'pacific'},
{'kaggle_id': 1335, 'team_name': "Penn", 'sports-reference': 'pennsylvania'},
{'kaggle_id': 1336, 'team_name': "Penn St", 'sports-reference': 'penn-state'},
{'kaggle_id': 1337, 'team_name': "Pepperdine", 'sports-reference': 'pepperdine'},
{'kaggle_id': 1338, 'team_name': "Pittsburgh", 'sports-reference': 'pittsburgh'},
{'kaggle_id': 1339, 'team_name': "Portland", 'sports-reference': 'portland'},
{'kaggle_id': 1340, 'team_name': "Portland St", 'sports-reference': 'portland-state'},
{'kaggle_id': 1341, 'team_name': "Prairie View", 'sports-reference': 'prairie-view'},
{'kaggle_id': 1342, 'team_name': "Presbyterian", 'sports-reference': 'presbyterian'},
{'kaggle_id': 1343, 'team_name': "Princeton", 'sports-reference': 'princeton'},
{'kaggle_id': 1344, 'team_name': "Providence", 'sports-reference': 'providence'},
{'kaggle_id': 1345, 'team_name': "Purdue", 'sports-reference': 'purdue'},
{'kaggle_id': 1346, 'team_name': "Quinnipiac", 'sports-reference': 'quinnipiac'},
{'kaggle_id': 1347, 'team_name': "Radford", 'sports-reference': 'radford'},
{'kaggle_id': 1348, 'team_name': "Rhode Island", 'sports-reference': 'rhode-island'},
{'kaggle_id': 1349, 'team_name': "Rice", 'sports-reference': 'rice'},
{'kaggle_id': 1350, 'team_name': "Richmond", 'sports-reference': 'richmond'},
{'kaggle_id': 1351, 'team_name': "Rider", 'sports-reference': 'rider'},
{'kaggle_id': 1352, 'team_name': "Robert Morris", 'sports-reference': 'robert-morris'},
{'kaggle_id': 1353, 'team_name': "Rutgers", 'sports-reference': 'rutgers'},
{'kaggle_id': 1354, 'team_name': "S Carolina St", 'sports-reference': 'south-carolina-state'},
{'kaggle_id': 1355, 'team_name': "S Dakota St", 'sports-reference': 'south-dakota-state'},
{'kaggle_id': 1356, 'team_name': "S Illinois", 'sports-reference': 'southern-illinois'},
{'kaggle_id': 1357, 'team_name': "Sacred Heart", 'sports-reference': 'sacred-heart'},
{'kaggle_id': 1358, 'team_name': "Sam Houston St", 'sports-reference': 'sam-houston-state'},
{'kaggle_id': 1359, 'team_name': "Samford", 'sports-reference': 'samford'},
{'kaggle_id': 1360, 'team_name': "San Diego", 'sports-reference': 'san-diego'},
{'kaggle_id': 1361, 'team_name': "San Diego St", 'sports-reference': 'san-diego-state'},
{'kaggle_id': 1362, 'team_name': "San Francisco", 'sports-reference': 'san-francisco'},
{'kaggle_id': 1363, 'team_name': "San Jose St", 'sports-reference': 'san-jose-state'},
{'kaggle_id': 1364, 'team_name': "Santa Barbara", 'sports-reference': 'california-santa-barbara'},
{'kaggle_id': 1365, 'team_name': "Santa Clara", 'sports-reference': 'santa-clara'},
{'kaggle_id': 1366, 'team_name': "Savannah St", 'sports-reference': 'savannah-state'},
{'kaggle_id': 1367, 'team_name': "SC Upstate", 'sports-reference': 'south-carolina-upstate'},
{'kaggle_id': 1368, 'team_name': "SE Louisiana", 'sports-reference': 'southeastern-louisiana'},
{'kaggle_id': 1369, 'team_name': "SE Missouri St", 'sports-reference': 'southeast-missouri-state'},
{'kaggle_id': 1370, 'team_name': "Seattle", 'sports-reference': 'seattle'},
{'kaggle_id': 1371, 'team_name': "Seton Hall", 'sports-reference': 'seton-hall'},
{'kaggle_id': 1372, 'team_name': "SF Austin", 'sports-reference': 'stephen-f-austin'},
{'kaggle_id': 1373, 'team_name': "Siena", 'sports-reference': 'siena'},
{'kaggle_id': 1374, 'team_name': "SMU", 'sports-reference': 'southern-methodist'},
{'kaggle_id': 1375, 'team_name': "South Alabama", 'sports-reference': 'south-alabama'},
{'kaggle_id': 1376, 'team_name': "South Carolina", 'sports-reference': 'south-carolina'},
{'kaggle_id': 1377, 'team_name': "South Dakota", 'sports-reference': 'south-dakota'},
{'kaggle_id': 1378, 'team_name': "South Florida", 'sports-reference': 'south-florida'},
{'kaggle_id': 1379, 'team_name': "Southern Miss", 'sports-reference': 'southern-mississippi'},
{'kaggle_id': 1380, 'team_name': "Southern Univ", 'sports-reference': 'southern'},
{'kaggle_id': 1381, 'team_name': "Southern Utah", 'sports-reference': 'southern-utah'},
{'kaggle_id': 1382, 'team_name': "St Bonaventure", 'sports-reference': 'st-bonaventure'},
{'kaggle_id': 1383, 'team_name': "St Francis NY", 'sports-reference': 'st-francis-ny'},
{'kaggle_id': 1384, 'team_name': "St Francis PA", 'sports-reference': 'saint-francis-pa'},
{'kaggle_id': 1385, 'team_name': "St John's", 'sports-reference': 'st-johns-ny'},
{'kaggle_id': 1386, 'team_name': "St Joseph's PA", 'sports-reference': 'saint-josephs'},
{'kaggle_id': 1387, 'team_name': "St Louis", 'sports-reference': 'saint-louis'},
{'kaggle_id': 1388, 'team_name': "St Mary's CA", 'sports-reference': 'saint-marys-ca'},
{'kaggle_id': 1389, 'team_name': "St Peter's", 'sports-reference': 'saint-peters'},
{'kaggle_id': 1390, 'team_name': "Stanford", 'sports-reference': 'stanford'},
{'kaggle_id': 1391, 'team_name': "Stetson", 'sports-reference': 'stetson'},
{'kaggle_id': 1392, 'team_name': "Stony Brook", 'sports-reference': 'stony-brook'},
{'kaggle_id': 1393, 'team_name': "Syracuse", 'sports-reference': 'syracuse'},
{'kaggle_id': 1394, 'team_name': "TAM C. Christi", 'sports-reference': 'texas-am-corpus-christi'},
{'kaggle_id': 1395, 'team_name': "TCU", 'sports-reference': 'texas-christian'},
{'kaggle_id': 1396, 'team_name': "Temple", 'sports-reference': 'temple'},
{'kaggle_id': 1397, 'team_name': "Tennessee", 'sports-reference': 'tennessee'},
{'kaggle_id': 1398, 'team_name': "Tennessee St", 'sports-reference': 'tennessee-state'},
{'kaggle_id': 1399, 'team_name': "Tennessee Tech", 'sports-reference': 'tennessee-tech'},
{'kaggle_id': 1400, 'team_name': "Texas", 'sports-reference': 'texas'},
{'kaggle_id': 1401, 'team_name': "Texas A&M", 'sports-reference': 'texas-am'},
{'kaggle_id': 1402, 'team_name': "Texas St", 'sports-reference': 'texas-state'},
{'kaggle_id': 1403, 'team_name': "Texas Tech", 'sports-reference': 'texas-tech'},
{'kaggle_id': 1404, 'team_name': "TN Martin", 'sports-reference': 'tennessee-martin'},
{'kaggle_id': 1405, 'team_name': "Toledo", 'sports-reference': 'toledo'},
{'kaggle_id': 1406, 'team_name': "Towson", 'sports-reference': 'towson'},
{'kaggle_id': 1407, 'team_name': "Troy", 'sports-reference': 'troy'},
{'kaggle_id': 1408, 'team_name': "Tulane", 'sports-reference': 'tulane'},
{'kaggle_id': 1409, 'team_name': "Tulsa", 'sports-reference': 'tulsa'},
{'kaggle_id': 1410, 'team_name': "UTRGV", 'sports-reference': 'texas-pan-american'},
{'kaggle_id': 1411, 'team_name': "TX Southern", 'sports-reference': 'texas-southern'},
{'kaggle_id': 1412, 'team_name': "UAB", 'sports-reference': 'alabama-birmingham'},
{'kaggle_id': 1413, 'team_name': "UC Davis", 'sports-reference': 'california-davis'},
{'kaggle_id': 1414, 'team_name': "UC Irvine", 'sports-reference': 'california-irvine'},
{'kaggle_id': 1415, 'team_name': "UC Riverside", 'sports-reference': 'california-riverside'},
{'kaggle_id': 1416, 'team_name': "UCF", 'sports-reference': 'central-florida'},
{'kaggle_id': 1417, 'team_name': "UCLA", 'sports-reference': 'ucla'},
{'kaggle_id': 1418, 'team_name': "ULL", 'sports-reference': 'louisiana-lafayette'},
{'kaggle_id': 1419, 'team_name': "ULM", 'sports-reference': 'louisiana-monroe'},
{'kaggle_id': 1420, 'team_name': "UMBC", 'sports-reference': 'maryland-baltimore-county'},
{'kaggle_id': 1421, 'team_name': "UNC Asheville", 'sports-reference': 'north-carolina-asheville'},
{'kaggle_id': 1422, 'team_name': "UNC Greensboro", 'sports-reference': 'north-carolina-greensboro'},
{'kaggle_id': 1423, 'team_name': "UNC Wilmington", 'sports-reference': 'north-carolina-wilmington'},
{'kaggle_id': 1424, 'team_name': "UNLV", 'sports-reference': 'nevada-las-vegas'},
{'kaggle_id': 1425, 'team_name': "USC", 'sports-reference': 'southern-california'},
{'kaggle_id': 1426, 'team_name': "UT Arlington", 'sports-reference': 'texas-arlington'},
{'kaggle_id': 1427, 'team_name': "UT San Antonio", 'sports-reference': 'texas-san-antonio'},
{'kaggle_id': 1428, 'team_name': "Utah", 'sports-reference': 'utah'},
{'kaggle_id': 1429, 'team_name': "Utah St", 'sports-reference': 'utah-state'},
{'kaggle_id': 1430, 'team_name': "Utah Valley", 'sports-reference': 'utah-valley'},
{'kaggle_id': 1431, 'team_name': "UTEP", 'sports-reference': 'texas-el-paso'},
{'kaggle_id': 1432, 'team_name': "Utica", 'sports-reference': 'utica'}, # gone in 1987
{'kaggle_id': 1433, 'team_name': "VA Commonwealth", 'sports-reference': 'virginia-commonwealth'},
{'kaggle_id': 1434, 'team_name': "Valparaiso", 'sports-reference': 'valparaiso'},
{'kaggle_id': 1435, 'team_name': "Vanderbilt", 'sports-reference': 'vanderbilt'},
{'kaggle_id': 1436, 'team_name': "Vermont", 'sports-reference': 'vermont'},
{'kaggle_id': 1437, 'team_name': "Villanova", 'sports-reference': 'villanova'},
{'kaggle_id': 1438, 'team_name': "Virginia", 'sports-reference': 'virginia'},
{'kaggle_id': 1439, 'team_name': "Virginia Tech", 'sports-reference': 'virginia-tech'},
{'kaggle_id': 1440, 'team_name': "VMI", 'sports-reference': 'virginia-military-institute'},
{'kaggle_id': 1441, 'team_name': "W Carolina", 'sports-reference': 'western-carolina'},
{'kaggle_id': 1442, 'team_name': "W Illinois", 'sports-reference': 'western-illinois'},
{'kaggle_id': 1443, 'team_name': "WKU", 'sports-reference': 'western-kentucky'},
{'kaggle_id': 1444, 'team_name': "W Michigan", 'sports-reference': 'western-michigan'},
#{'kaggle_id': 1445, 'team_name': "W Salem St", 'sports-reference': ''  -- no idea who this is
{'kaggle_id': 1446, 'team_name': "W Texas A&M", 'sports-reference': 'west-texas-am'}, # gone in 1986
{'kaggle_id': 1447, 'team_name': "Wagner", 'sports-reference': 'wagner'},
{'kaggle_id': 1448, 'team_name': "Wake Forest", 'sports-reference': 'wake-forest'},
{'kaggle_id': 1449, 'team_name': "Washington", 'sports-reference': 'washington'},
{'kaggle_id': 1450, 'team_name': "Washington St", 'sports-reference': 'washington-state'},
{'kaggle_id': 1451, 'team_name': "Weber St", 'sports-reference': 'weber-state'},
{'kaggle_id': 1452, 'team_name': "West Virginia", 'sports-reference': 'west-virginia'},
{'kaggle_id': 1453, 'team_name': "WI Green Bay", 'sports-reference': 'green-bay'},
{'kaggle_id': 1454, 'team_name': "WI Milwaukee", 'sports-reference': 'milwaukee'},
{'kaggle_id': 1455, 'team_name': "Wichita St", 'sports-reference': 'wichita-state'},
{'kaggle_id': 1456, 'team_name': "William & Mary", 'sports-reference': 'william-mary'},
{'kaggle_id': 1457, 'team_name': "Winthrop", 'sports-reference': 'winthrop'},
{'kaggle_id': 1458, 'team_name': "Wisconsin", 'sports-reference': 'wisconsin'},
{'kaggle_id': 1459, 'team_name': "Wofford", 'sports-reference': 'wofford'},
{'kaggle_id': 1460, 'team_name': "Wright St", 'sports-reference': 'wright-state'},
{'kaggle_id': 1461, 'team_name': "Wyoming", 'sports-reference': 'wyoming'},
{'kaggle_id': 1462, 'team_name': "Xavier", 'sports-reference': 'xavier'},
{'kaggle_id': 1463, 'team_name': "Yale", 'sports-reference': 'yale'},
{'kaggle_id': 1464, 'team_name': "Youngstown St", 'sports-reference' :'youngstown-state'}]
