# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /Users/travis/build/conda-forge/numpy-feedstock/recipe, last modified Fri Jul  7 09:41:30 2017
# ------------------------------------------------

package:
    name: numpy
    version: 1.13.1
source:
    fn: numpy-1.13.1.tar.gz
    sha256: cf8652b96582b282a5bb710aa4fe2300dca63bdd678a3cd7820314cb6c97ca89
    url: https://github.com/numpy/numpy/archive/v1.13.1.tar.gz
build:
    features:
        - blas_openblas
    noarch: ''
    noarch_python: false
    number: '200'
    string: py27_blas_openblas_200
requirements:
    build:
        - blas 1.1 openblas
        - ca-certificates 2017.4.17 0
        - certifi 2017.4.17 py27_0
        - cython 0.25.2 py27_1
        - libgfortran 3.0.0 0
        - ncurses 5.9 10
        - openblas 0.2.19 2
        - openssl 1.0.2l 0
        - python 2.7.13 1
        - readline 6.2 0
        - setuptools 33.1.1 py27_0
        - sqlite 3.13.0 1
        - tk 8.5.19 1
        - toolchain 2.0.0 0
        - zlib 1.2.11 0
    run:
        - python
        - blas 1.1 openblas
        - openblas 0.2.19|0.2.19.*
test:
    commands:
        - f2py -h
    imports:
        - numpy
        - numpy.linalg.lapack_lite
    requires:
        - nose
about:
    home: http://numpy.scipy.org/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Array processing for numbers, strings, records, and objects.
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - pelson
        - rgommers
        - ocefpaf
