# This file created by conda-build 2.1.15
# meta.yaml template originally from:
# /Users/travis/build/conda-forge/theano-feedstock/recipe, last modified Thu Jun 22 17:16:16 2017
# ------------------------------------------------

package:
    name: theano
    version: 0.9.0
source:
    fn: Theano-0.9.0.tar.gz
    sha256: 745d66716531f9063127274b40503fbc21f931f78b7b03e79e5523d50078bc17
    url: https://pypi.io/packages/source/T/Theano/Theano-0.9.0.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '1'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py27_1
requirements:
    build:
        - ca-certificates 2017.4.17 0
        - certifi 2017.4.17 py27_0
        - ncurses 5.9 10
        - openssl 1.0.2k 0
        - python 2.7.13 1
        - readline 6.2 0
        - setuptools 33.1.1 py27_0
        - sqlite 3.13.0 1
        - tk 8.5.19 1
        - zlib 1.2.11 0
    run:
        - python
        - six >=1.9.0
        - numpy >=1.9.1
        - scipy >=0.14
        - pygpu >=0.6.5
test:
    imports:
        - theano
        - theano.compile
        - theano.compile.sandbox
        - theano.compile.tests
        - theano.gof
        - theano.gof.tests
        - theano.misc
        - theano.sandbox
        - theano.sandbox.cuda
        - theano.sandbox.cuda.tests
        - theano.scalar
        - theano.scalar.tests
        - theano.sparse
        - theano.sparse.tests
        - theano.tensor
        - theano.tensor.nnet
        - theano.tensor.nnet.tests
        - theano.tensor.signal
        - theano.tensor.signal.tests
        - theano.tensor.tests
        - theano.tests
    requires:
        - nose >=1.3.0
        - nose_parameterized >=0.5.0
about:
    home: http://deeplearning.net/software/theano/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Optimizing compiler for evaluating mathematical expressions on CPUs and
        GPUs.
extra:
    final: true
    recipe-maintainers:
        - abergeron
        - jakirkham
        - ocefpaf
        - ericmjl
