# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /Users/travis/build/conda-forge/pygpu-feedstock/recipe, last modified Thu Jul 27 02:02:34 2017
# ------------------------------------------------

package:
    name: pygpu
    version: 0.6.9
source:
    fn: libgpuarray-0.6.9.tar.gz
    sha256: 689716feecb4e495f4d383ec1518cf3ba70a2a642a903cc445b6b6ffc119bc25
    url: https://github.com/Theano/libgpuarray/archive/v0.6.9.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    script:
        - export CFLAGS="${CFLAGS} -I${PREFIX}/include -L${PREFIX}/lib"
        - python setup.py install --single-version-externally-managed --record record.txt
    string: np113py27_0
requirements:
    build:
        - blas 1.1 openblas
        - ca-certificates 2017.4.17 0
        - certifi 2017.4.17 py27_0
        - cython 0.26 py27_0
        - libgfortran 3.0.0 0
        - libgpuarray 0.6.9 0
        - mako 1.0.7 py27_0
        - markupsafe 1.0 py27_0
        - ncurses 5.9 10
        - numpy 1.13.1 py27_blas_openblas_201
        - openblas 0.2.20 1
        - openssl 1.0.2l 0
        - python 2.7.13 1
        - readline 6.2 0
        - setuptools 36.2.2 py27_0
        - sqlite 3.13.0 1
        - tk 8.5.19 1
        - toolchain 2.0.0 0
        - zlib 1.2.11 0
    run:
        - python
        - numpy x.x
        - mako
        - six
        - libgpuarray ==0.6.9
test:
    imports:
        - pygpu
        - pygpu.gpuarray
about:
    dev_url: http://github.com/Theano/libgpuarray
    doc_url: http://deeplearning.net/software/libgpuarray/
    home: http://github.com/Theano/libgpuarray
    license: ISC
    license_file: LICENSE
    summary: Library to manipulate arrays on GPU
extra:
    final: true
    recipe-maintainers:
        - abergeron
