# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /Users/travis/build/conda-forge/mako-feedstock/recipe, last modified Fri Jul 14 17:38:51 2017
# ------------------------------------------------

package:
    name: mako
    version: 1.0.7
source:
    fn: Mako-1.0.7.tar.gz
    sha256: 4e02fde57bd4abb5ec400181e4c314f56ac3e49ba4fb8b0d50bba18cb27d25ae
    url: https://pypi.io/packages/source/M/Mako/Mako-1.0.7.tar.gz
build:
    entry_points:
        - mako-render=mako.cmd:cmdline
    noarch: ''
    noarch_python: false
    number: '0'
    preserve_egg_dir: 'True'
    script: python setup.py install
    string: py27_0
requirements:
    build:
        - ca-certificates 2017.4.17 0
        - certifi 2017.4.17 py27_0
        - markupsafe 1.0 py27_0
        - ncurses 5.9 10
        - openssl 1.0.2l 0
        - python 2.7.13 1
        - readline 6.2 0
        - setuptools 33.1.1 py27_0
        - sqlite 3.13.0 1
        - tk 8.5.19 1
        - zlib 1.2.11 0
    run:
        - python
        - markupsafe >=0.9.2
test:
    commands:
        - mako-render --help
    imports:
        - mako
        - mako.ext
about:
    dev_url: https://bitbucket.org/zzzeek/mako/src
    doc_url: http://docs.makotemplates.org/en/latest/
    home: http://www.makotemplates.org/
    license: MIT
    license_file: LICENSE
    summary: A super-fast templating language that borrows the best ideas from the
        existing templating languages.
extra:
    final: true
    recipe-maintainers:
        - Korijn
        - pmlandwehr
