# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /Users/travis/build/conda-forge/hdf5-feedstock/recipe, last modified Wed Aug  9 03:11:33 2017
# ------------------------------------------------

package:
    name: hdf5
    version: 1.8.18
source:
    patches:
        - test_Makefile.in.patch
        - osx_configure.patch
    sha256: cdb195ad8d9e6782acf24b2488061289f615628c2ccda8457b0a0c3fb7a8a063
    url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.18/src/hdf5-1.8.18.tar.gz
build:
    detect_binary_files_with_prefix: 'True'
    features: ''
    noarch: ''
    noarch_python: false
    number: '1'
    string: '1'
requirements:
    build:
        - bzip2 1.0.6 1
        - ca-certificates 2017.7.27.1 0
        - cloog 0.18.0 0
        - cmake 3.9.0 0
        - curl 7.54.1 0
        - expat 2.2.1 0
        - gcc 4.8.5 8
        - gmp 6.1.2 0
        - isl 0.12.2 1
        - krb5 1.14.2 0
        - libssh2 1.8.0 1
        - libtool 2.4.6 0
        - libuv 1.11.0 0
        - mpc 1.0.3 4
        - mpfr 3.1.5 0
        - ncurses 5.9 10
        - openssl 1.0.2l 0
        - rhash 1.3.4 0
        - toolchain 2.0.0 0
        - xz 5.2.2 0
        - zlib 1.2.8 3
    run:
        - zlib 1.2.8
        - libgfortran
test:
    commands:
        - command -v h5c++
        - command -v h5cc
        - command -v h5perf_serial
        - command -v h5redeploy
        - command -v h5fc
        - command -v gif2h5
        - command -v h52gif
        - command -v h5copy
        - command -v h5debug
        - command -v h5diff
        - command -v h5dump
        - command -v h5import
        - command -v h5jam
        - command -v h5ls
        - command -v h5mkgrp
        - command -v h5repack
        - command -v h5repart
        - command -v h5stat
        - command -v h5unjam
        - test -f $PREFIX/lib/libhdf5.a
        - test -f $PREFIX/lib/libhdf5.dylib
        - test -f $PREFIX/lib/libhdf5_cpp.a
        - test -f $PREFIX/lib/libhdf5_cpp.dylib
        - test -f $PREFIX/lib/libhdf5_hl.a
        - test -f $PREFIX/lib/libhdf5_hl.dylib
        - test -f $PREFIX/lib/libhdf5_hl_cpp.a
        - test -f $PREFIX/lib/libhdf5_hl_cpp.dylib
        - conda inspect linkages -p $PREFIX hdf5
        - conda inspect objects -p $PREFIX hdf5
    files:
        - h5_cmprss.c
        - h5tutr_cmprss.cpp
        - h5_cmprss.f90
        - compound_fortran2003.f90
    requires:
        - gcc
about:
    home: http://www.hdfgroup.org/HDF5/
    license: HDF5
    license_family: BSD
    license_file: COPYING
    summary: HDF5 is a data model, library, and file format for storing and managing
        data.
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - gillins
        - groutr
        - ocefpaf
        - astrofrog
        - marqh
