# This file created by conda-build 2.1.9
# meta.yaml template originally from:
# /Users/travis/build/conda-forge/openblas-feedstock/recipe, last modified Mon Apr 17 11:09:58 2017
# ------------------------------------------------

package:
    name: openblas
    version: 0.2.19
source:
    fn: openblas-0.2.19.tar.gz
    patches:
        - pkg-config.patch
    sha256: 9c40b5e4970f27c5f6911cb0a28aa26b6c83f17418b69f8e5a116bb983ca8557
    url: https://github.com/xianyi/OpenBLAS/archive/v0.2.19.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '2'
    string: '2'
    track_features: ''
requirements:
    build:
        - cloog 0.18.0 0
        - gcc 4.8.5 8
        - gmp 6.1.2 0
        - isl 0.12.2 1
        - mpc 1.0.3 3
        - mpfr 3.1.5 0
        - perl 5.22.2.1 0
        - toolchain 2.0.0 0
    run:
        - libgfortran
test:
    commands:
        - test -f ${PREFIX}/lib/libopenblas.a
        - test -f ${PREFIX}/lib/libopenblas.dylib
about:
    home: http://www.openblas.net/
    license: BSD 3-Clause
    summary: An optimized BLAS library based on GotoBLAS2 1.13 BSD version.
extra:
    final: true
    recipe-maintainers:
        - gillins
        - groutr
        - jakirkham
        - jschueller
