# This file created by conda-build 2.1.10
# meta.yaml template originally from:
# /Users/travis/build/conda-forge/markupsafe-feedstock/recipe, last modified Mon May 22 18:00:13 2017
# ------------------------------------------------

package:
    name: markupsafe
    version: '1.0'
source:
    fn: MarkupSafe-1.0.tar.gz
    sha256: a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665
    url: https://pypi.io/packages/source/M/MarkupSafe/MarkupSafe-1.0.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py27_0
requirements:
    build:
        - ca-certificates 2017.4.17 0
        - certifi 2017.4.17 py27_0
        - ncurses 5.9 10
        - openssl 1.0.2k 0
        - python 2.7.13 1
        - readline 6.2 0
        - setuptools 33.1.1 py27_0
        - sqlite 3.13.0 1
        - tk 8.5.19 1
        - zlib 1.2.11 0
    run:
        - python
test:
    imports:
        - markupsafe
about:
    dev_url: https://github.com/pallets/markupsafe
    home: https://www.palletsprojects.com/p/markupsafe/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A Python module that implements the jinja2.Markup string
extra:
    final: true
    recipe-maintainers:
        - pelson
        - scopatz
