# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /Users/travis/build/conda-forge/conda-feedstock/recipe, last modified Thu Aug 10 00:36:34 2017
# ------------------------------------------------

package:
    name: conda
    version: 4.3.23
source:
    fn: conda-4.3.23.tar.gz
    sha256: 9c2b8031c75f94299df2762f047dab0661fffc102269587e2b0913624c15d885
    url: https://github.com/conda/conda/archive/4.3.23.tar.gz
build:
    always_include_files:
        - bin/conda
        - bin/activate
        - bin/deactivate
    entry_points:
        - conda = conda.cli:main
        - conda-env = conda_env.cli.main:main
    noarch: ''
    noarch_python: false
    number: '0'
    string: py27_0
requirements:
    build:
        - ca-certificates 2017.7.27.1 0
        - ncurses 5.9 10
        - openssl 1.0.2l 0
        - python 2.7.13 1
        - readline 6.2 0
        - sqlite 3.13.0 1
        - tk 8.5.19 2
        - zlib 1.2.11 0
    run:
        - python
        - conda-env >=2.6
        - enum34
        - pycosat >=0.6.1
        - pyopenssl >=16.2.0
        - requests >=2.12.4
        - ruamel_yaml >=0.11.14
test:
    commands:
        - python -c "from __future__ import print_function; import conda; print(conda.__version__)"
        - which conda
        - which conda-env
        - conda --version
        - conda info
        - conda env --help
    imports:
        - conda
about:
    description: 'Conda is an open source package management system and environment

        management system for installing multiple versions of software packages

        and their dependencies and switching easily between them. It works on

        Linux, OS X and Windows, and was created for Python programs but can

        package and distribute any software.

        '
    dev_url: https://github.com/conda/conda
    doc_url: http://conda.pydata.org/docs/
    home: http://conda.pydata.org/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: OS-agnostic, system-level binary package and environment manager.
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - kalefranz
        - mcg1969
        - mingwandroid
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
