# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /Users/travis/build/conda-forge/python-dateutil-feedstock/recipe, last modified Wed Jul 19 19:39:12 2017
# ------------------------------------------------

package:
    name: python-dateutil
    version: 2.6.1
source:
    fn: python-dateutil-2.6.1.tar.gz
    sha256: 891c38b2a02f5bb1be3e4793866c8df49c7d19baabf9c1bad62547e0b4866aca
    url: https://pypi.io/packages/source/p/python-dateutil/python-dateutil-2.6.1.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py27_0
requirements:
    build:
        - ca-certificates 2017.4.17 0
        - certifi 2017.4.17 py27_0
        - ncurses 5.9 10
        - openssl 1.0.2l 0
        - python 2.7.13 1
        - readline 6.2 0
        - setuptools 33.1.1 py27_0
        - sqlite 3.13.0 1
        - tk 8.5.19 1
        - zlib 1.2.11 0
    run:
        - python
        - six
test:
    imports:
        - dateutil
        - dateutil.rrule
about:
    description: 'The dateutil module provides powerful extensions to the standard
        datetime

        module, available in Python.

        '
    dev_url: https://github.com/dateutil/dateutil/
    doc_url: https://dateutil.readthedocs.org/en/latest/
    home: https://dateutil.readthedocs.org/
    license: BSD 3-clause
    license_file: LICENSE
    summary: Extensions to the standard Python datetime module.
extra:
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
