# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /Users/travis/build/conda-forge/pandas-feedstock/recipe, last modified Sat Jul 15 23:07:42 2017
# ------------------------------------------------

package:
    name: pandas
    version: 0.20.3
source:
    fn: pandas-0.20.3.tar.gz
    sha256: a777e07633d83d546c55706420179551c8e01075b53c497dcf8ae4036766bc66
    url: https://github.com/pandas-dev/pandas/releases/download/v0.20.3/pandas-0.20.3.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py27_1
requirements:
    build:
        - ca-certificates 2017.4.17 0
        - certifi 2017.4.17 py27_0
        - cython 0.25.2 py27_1
        - ncurses 5.9 10
        - numpy 1.7.1 py27_2
        - openssl 1.0.2l 0
        - python 2.7.13 1
        - readline 6.2 0
        - setuptools 33.1.1 py27_0
        - sqlite 3.13.0 1
        - tk 8.5.19 1
        - zlib 1.2.11 0
    run:
        - python
        - numpy >=1.7
        - python-dateutil
        - pytz
test:
    commands:
        - conda inspect linkages -p $PREFIX pandas
        - conda inspect objects -p $PREFIX pandas
    imports:
        - pandas
about:
    home: http://pandas.pydata.org
    license: BSD 3-clause
    license_file: LICENSE
    summary: High-performance, easy-to-use data structures and data analysis tools.
extra:
    final: true
    recipe-maintainers:
        - jreback
        - jorisvandenbossche
        - msarahan
        - ocefpaf
        - TomAugspurger
