# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /Users/travis/build/conda-forge/scikit-learn-feedstock/recipe, last modified Fri Aug 11 22:46:11 2017
# ------------------------------------------------

package:
    name: scikit-learn
    version: 0.19.0
source:
    sha256: 25a889df32b9b3353f990726b54b6dc3e52a871ae8aea42e1f49d6726226f83c
    url: https://github.com/scikit-learn/scikit-learn/archive/0.19.0.tar.gz
build:
    features:
        - blas_openblas
    noarch: ''
    noarch_python: false
    number: '201'
    string: py27_blas_openblas_201
requirements:
    build:
        - blas 1.1 openblas
        - ca-certificates 2017.7.27.1 0
        - certifi 2017.7.27.1 py27_0
        - cython 0.26 py27_0
        - libgfortran 3.0.0 0
        - ncurses 5.9 10
        - nose 1.3.7 py27_2
        - numpy 1.9.3 py27_blas_openblas_202
        - openblas 0.2.19 2
        - openssl 1.0.2l 0
        - python 2.7.13 1
        - readline 6.2 0
        - scipy 0.19.1 py27_blas_openblas_202
        - setuptools 36.2.2 py27_0
        - sqlite 3.13.0 1
        - tk 8.5.19 2
        - zlib 1.2.11 0
    run:
        - python
        - blas 1.1 openblas
        - openblas 0.2.19|0.2.19.*
        - numpy >=1.9
        - scipy
test:
    commands:
        - nosetests sklearn --exe
        - conda inspect linkages -p $PREFIX scikit-learn
        - conda inspect objects -p $PREFIX scikit-learn
    imports:
        - sklearn
    requires:
        - nose
about:
    home: http://scikit-learn.org/
    license: BSD 3-Clause
    license_file: COPYING
    summary: A set of python modules for machine learning and data mining
extra:
    final: true
    recipe-maintainers:
        - amueller
        - astaric
        - jakirkham
        - ogrisel
        - ocefpaf
        - lesteve
